# Generated by Django 3.1.6 on 2021-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('source_full_description', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
    ]
