# Generated by Django 3.2.5 on 2021-07-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances_type', models.CharField(max_length=250, verbose_name='Тип прибора')),
                ('appliances_model', models.TextField(verbose_name='Модели')),
                ('appliances_paramerts', models.CharField(max_length=300, verbose_name='Параметры')),
                ('appliances_manufacturer', models.CharField(max_length=300, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
            },
        ),
        migrations.CreateModel(
            name='Measurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurable_parametrs', models.CharField(max_length=250, null=True, verbose_name='Параметр')),
                ('measurable_value', models.CharField(max_length=250, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Название измерямого параметра',
                'verbose_name_plural': 'Названия измеряемых параметров',
            },
        ),
        migrations.CreateModel(
            name='Expirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment_scheme', models.ImageField(upload_to='images/', verbose_name='Схема эксперимента')),
                ('measurements', models.CharField(max_length=100, verbose_name='Размеры (метры)')),
                ('places', models.CharField(max_length=250, verbose_name='Научный центр')),
                ('configurate_liquid', models.CharField(max_length=200, null=True, verbose_name='Конфигурация жидкости')),
                ('effects', models.CharField(max_length=300, verbose_name='Эффект')),
                ('appliance', models.ManyToManyField(to='DB.Appliances', verbose_name='Приборы')),
                ('measurable', models.ManyToManyField(to='DB.Measurable', verbose_name='Измеряемые параметры')),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='DB.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Эксперимент',
                'verbose_name_plural': 'Эксперименты',
            },
        ),
    ]
