# Generated by Django 3.2.5 on 2021-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_appliances_expirement_measurable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirement',
            name='measured_param',
            field=models.CharField(max_length=300, null=True, verbose_name='Измеряемые параметры'),
        ),
    ]
